# Generated by Django 5.1 on 2025-01-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountant',
            name='unpaid_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='first_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Employee_images'),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='last_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
