# Generated by Django 5.1 on 2025-01-16 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_term_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='active_year',
            field=models.BooleanField(help_text='DANGER!! This is the current school year. There can only be one and setting this will remove it from other years. If you want to change the active year, click Admin, Change School Year.'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='active',
            field=models.BooleanField(default=False, help_text='DANGER..!!!! If marked, this will be the default School Information System Wide...'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['login'], name='administrat_login_i_b9be62_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['date'], name='administrat_date_0e2943_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='administrat_name_c974a6_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['active'], name='administrat_active_1f2ae9_idx'),
        ),
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='administration.academicyear'),
        ),
    ]
