# Generated by Django 5.1 on 2025-01-16 12:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_remove_teacher_teacher_id_student_prem_number'),
        ('administration', '0003_term_alter_school_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentspreviousacademichistory',
            old_name='students_name',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='student',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='unpaid_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=40),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.gradelevel'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='occupied_sits',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='order_rank',
            field=models.IntegerField(blank=True, help_text='Rank for course reports', null=True),
        ),
        migrations.AlterField(
            model_name='messagetoparent',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messagetoparent',
            name='message',
            field=models.TextField(help_text='Message to be shown to Parents.'),
        ),
        migrations.AlterField(
            model_name='messagetoparent',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messagetoteacher',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='messagetoteacher',
            name='message',
            field=models.TextField(help_text='Message to be shown to Teachers.'),
        ),
        migrations.AlterField(
            model_name='messagetoteacher',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parent',
            name='alt_email',
            field=models.EmailField(blank=True, help_text='Personal email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='monthly_income',
            field=models.FloatField(blank=True, help_text="Parent's average monthly income", null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='occupation',
            field=models.CharField(blank=True, help_text='Current occupation', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(help_text='Personal phone number', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='single_parent',
            field=models.BooleanField(blank=True, default=False, help_text='Is he/she a single parent'),
        ),
        migrations.AlterField(
            model_name='result',
            name='term',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, upload_to='Student_images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='academic.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentfile',
            name='file',
            field=models.FileField(upload_to='students_files/%(student_id)s/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='studentsmedicalhistory',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentspreviousacademichistory',
            name='notes',
            field=models.CharField(blank=True, help_text="Indicate student's academic performance according to your observation", max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='graded',
            field=models.BooleanField(default=True, help_text='Teachers can submit grades'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_selectable',
            field=models.BooleanField(default=False, help_text='Select if subject is optional'),
        ),
        migrations.AlterField(
            model_name='subjectallocation',
            name='term',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.term'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Employee_images'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('name', 'stream'), name='unique_classroom'),
        ),
    ]
